/*
============================================================
Exploratory Data Analysis (EDA)
============================================================
This script performs exploratory analysis on the Gold Layer 
of the data warehouse. It includes database structure review, 
dimension and measure exploration, date range validation, 
key business metrics calculation, magnitude analysis, and 
ranking analysis to evaluate sales performance, customer 
behavior, and product revenue contribution.
============================================================
*/

--=========================
-- Database Exploration!
--=========================
-- Explore all objects in the Database (through system information)
SELECT *
FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the Database
SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--=========================
-- Dimensions Exploration!
--=========================
-- Explore all countries our customers come from.
SELECT DISTINCT country
FROM gold.dim_customers

-- Explore all categories 'The major Divisions'
SELECT DISTINCT 
	category,
	subcategory,
	product_name
FROM gold.dim_products
ORDER BY 1, 2, 3

--=========================
-- Date Exploration!
--=========================
-- Find the date of the first and last order
-- How many years of sales are available
SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
FROM gold.fact_sales

-- Find the youngest and oldest customer
SELECT 
	MIN(birthdate) AS oldest_customer,
	MAX(birthdate) AS youngest_customer,
	DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_customer_age,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_customer_age
FROM gold.dim_customers

--=========================
-- Measures Exploration!
--=========================
-- Find the Total Sales
SELECT
	SUM(sales_amount) AS total_sales
FROM gold.fact_sales

-- Find how many items are sold
SELECT
	SUM(quantity) AS total_quantity
FROM gold.fact_sales

-- Find the average selling price
SELECT 
	AVG(price) AS avg_price
FROM gold.fact_sales

-- Find the total number of Orders
SELECT
	COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales

-- Find the total number of products
SELECT 
	COUNT(DISTINCT product_name) AS total_products
FROM gold.dim_products

-- Find the total number of customers
SELECT 
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers

-- Find the total number of customers that has placed an order
SELECT
	COUNT(DISTINCT customer_key) AS customers_with_orders
FROM gold.fact_sales

--..............................................................
-- Generate a report that shows all key metrics of the business.
--..............................................................
SELECT 
	'Total Sales' AS measure_name,
	SUM(sales_amount) AS measure_value
FROM gold.fact_sales
UNION ALL
SELECT 
	'Total Quantity',
	SUM(quantity)
FROM gold.fact_sales
UNION ALL
SELECT 
	'Average Price',
	AVG(price)
FROM gold.fact_sales
UNION ALL
SELECT 
	'Total Nr. Orders',
	COUNT(DISTINCT order_number)
FROM gold.fact_sales
UNION ALL
SELECT 
	'Total Nr. Products',
	COUNT(product_name)
FROM gold.dim_products
UNION ALL 
SELECT 
	'Total Nr. Customers',
	COUNT(customer_key)
FROM gold.dim_customers

--=========================
-- Magnitude Analysis!
--=========================
-- Find total customers by countries
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT 
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT 
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated for each category?
SELECT 
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- What is the total revenue generated by each customer?
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of items sold items across countries?
SELECT 
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

--=========================
-- Ranking Analysis
--=========================
-- Which 5 products generate the highest revenue?
SELECT TOP 5
	p.product_key,
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.product_key, p.product_name
ORDER BY total_revenue DESC

--OR (By using Window function)

SELECT * 
FROM (
	SELECT
		p.product_key,
		p.product_name,
		SUM(f.sales_amount) AS total_revenue,
		ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales AS f
	LEFT JOIN gold.dim_products AS p
	ON f.product_key = p.product_key
	GROUP BY p.product_key, p.product_name
)t 
WHERE rank_products < 6

-- What are the 5 worst-performing products in terms of sales
SELECT TOP 5
	p.product_key,
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.product_key, p.product_name
ORDER BY total_revenue ASC

-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC

-- The 3 customers with the fewest orders placed
SELECT TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT f.order_number) AS total_orders
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_orders ASC

